<?php
/**
 * 测试控制器类
 * @author ztt
 * @date 2017/10/30
 */
namespace app\controllers;

use Yii;
use app\components\Controller;
use app\models\Black;
use app\models\CommentT;
use app\models\FilmSpider;

class TestController extends Controller {
    public function actionA() {
        $connomains = array(
        'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
            'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
            'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
             'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
            'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
            'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
             'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
            'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
            'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
             'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
            'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
            'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
             'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
            'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
            'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
             'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
            'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
            'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
             'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
            'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
            'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
             'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
            'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
            'http://yytest.leiyu.tv/index.php?r=comment/del&safe_code=44f249b517ecadd309b2ba890797447b&code=6fd2841e3915e85e12bf8945fffd2a0f&from=1&cid=9',
        );
        $mh = curl_multi_init();
        foreach ($connomains as $i => $url) {
             $conn[$i]=curl_init($url);
              curl_setopt($conn[$i],CURLOPT_RETURNTRANSFER,1);
              curl_multi_add_handle ($mh,$conn[$i]);
        }
        do { $n=curl_multi_exec($mh,$active); } while ($active);
        foreach ($connomains as $i => $url) {
              $res[$i]=curl_multi_getcontent($conn[$i]);
              curl_close($conn[$i]);
        }
        print_r($res);
        
    }
    
    public function actionC() {
        $url = 'http://127.0.0.2/spider/savefilm';
        $data = [
            'data'=>'{
    "resource":"去看TV",
    "title":"延禧攻略",
    "kind":"2",
    "status":"连载24集",
    "main_actor":[
        "秦岚,聂远,佘诗曼,吴谨言"
    ],
    "director":[

    ],
    "genre":[
        "国产剧"
    ],
    "cover":"http://pic.china-gif.com/pic/upload/vod/2018-07/15320077380.jpg",
    "area":"大陆",
    "year":"2018",
    "summary":"乾隆六年，少女魏璎珞为寻求长姐死亡真相，入紫禁城为宫女。经调查，璎珞证实姐姐之死与荒唐王爷弘昼有关，立志要讨回公道。富察皇后娴于礼法，担心璎珞走上歧途，竭力给予她",
    "play_route":[
        "云播K",
        "云播CK",
        "云播B",
        "云播3",
        "云播33K",
        "云播13K"
    ],
    "play_source":[
        {
            "way":[
                {
                    "title":"第24集",
                    "num":"24",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-24.html"
                },
                {
                    "title":"第23集",
                    "num":"23",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-23.html"
                },
                {
                    "title":"第22集",
                    "num":"22",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-22.html"
                },
                {
                    "title":"第21集",
                    "num":"21",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-21.html"
                },
                {
                    "title":"第20集",
                    "num":"20",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-20.html"
                },
                {
                    "title":"第19集",
                    "num":"19",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-19.html"
                },
                {
                    "title":"第18集",
                    "num":"18",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-18.html"
                },
                {
                    "title":"第17集",
                    "num":"17",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-17.html"
                },
                {
                    "title":"第16集",
                    "num":"16",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-16.html"
                },
                {
                    "title":"第15集",
                    "num":"15",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-15.html"
                },
                {
                    "title":"第14集",
                    "num":"14",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-14.html"
                },
                {
                    "title":"第13集",
                    "num":"13",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-13.html"
                },
                {
                    "title":"第12集",
                    "num":"12",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-12.html"
                },
                {
                    "title":"第11集",
                    "num":"11",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-11.html"
                },
                {
                    "title":"第10集",
                    "num":"10",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-10.html"
                },
                {
                    "title":"第09集",
                    "num":"9",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-9.html"
                },
                {
                    "title":"第08集",
                    "num":"8",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-8.html"
                },
                {
                    "title":"第07集",
                    "num":"7",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-7.html"
                },
                {
                    "title":"第06集",
                    "num":"6",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-6.html"
                },
                {
                    "title":"第05集",
                    "num":"5",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-5.html"
                },
                {
                    "title":"第04集",
                    "num":"4",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-4.html"
                },
                {
                    "title":"第03集",
                    "num":"3",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-3.html"
                },
                {
                    "title":"第02集",
                    "num":"2",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-2.html"
                },
                {
                    "title":"第01集",
                    "num":"1",
                    "url":"http://qukantv.net/vod-play-id-52541-src-1-num-1.html"
                }
            ]
        },
        {
            "way":[
                {
                    "title":"第24集",
                    "num":"24",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-24.html"
                },
                {
                    "title":"第23集",
                    "num":"23",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-23.html"
                },
                {
                    "title":"第22集",
                    "num":"22",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-22.html"
                },
                {
                    "title":"第21集",
                    "num":"21",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-21.html"
                },
                {
                    "title":"第20集",
                    "num":"20",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-20.html"
                },
                {
                    "title":"第19集",
                    "num":"19",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-19.html"
                },
                {
                    "title":"第18集",
                    "num":"18",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-18.html"
                },
                {
                    "title":"第17集",
                    "num":"17",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-17.html"
                },
                {
                    "title":"第16集",
                    "num":"16",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-16.html"
                },
                {
                    "title":"第15集",
                    "num":"15",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-15.html"
                },
                {
                    "title":"第14集",
                    "num":"14",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-14.html"
                },
                {
                    "title":"第13集",
                    "num":"13",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-13.html"
                },
                {
                    "title":"第12集",
                    "num":"12",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-12.html"
                },
                {
                    "title":"第11集",
                    "num":"11",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-11.html"
                },
                {
                    "title":"第10集",
                    "num":"10",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-10.html"
                },
                {
                    "title":"第09集",
                    "num":"9",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-9.html"
                },
                {
                    "title":"第08集",
                    "num":"8",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-8.html"
                },
                {
                    "title":"第07集",
                    "num":"7",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-7.html"
                },
                {
                    "title":"第06集",
                    "num":"6",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-6.html"
                },
                {
                    "title":"第05集",
                    "num":"5",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-5.html"
                },
                {
                    "title":"第04集",
                    "num":"4",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-4.html"
                },
                {
                    "title":"第03集",
                    "num":"3",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-3.html"
                },
                {
                    "title":"第02集",
                    "num":"2",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-2.html"
                },
                {
                    "title":"第01集",
                    "num":"1",
                    "url":"http://qukantv.net/vod-play-id-52541-src-2-num-1.html"
                }
            ]
        },
        {
            "way":[
                {
                    "title":"第24集",
                    "num":"24",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-24.html"
                },
                {
                    "title":"第23集",
                    "num":"23",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-23.html"
                },
                {
                    "title":"第22集",
                    "num":"22",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-22.html"
                },
                {
                    "title":"第21集",
                    "num":"21",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-21.html"
                },
                {
                    "title":"第20集",
                    "num":"20",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-20.html"
                },
                {
                    "title":"第19集",
                    "num":"19",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-19.html"
                },
                {
                    "title":"第18集",
                    "num":"18",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-18.html"
                },
                {
                    "title":"第17集",
                    "num":"17",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-17.html"
                },
                {
                    "title":"第16集",
                    "num":"16",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-16.html"
                },
                {
                    "title":"第15集",
                    "num":"15",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-15.html"
                },
                {
                    "title":"第14集",
                    "num":"14",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-14.html"
                },
                {
                    "title":"第13集",
                    "num":"13",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-13.html"
                },
                {
                    "title":"第12集",
                    "num":"12",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-12.html"
                },
                {
                    "title":"第11集",
                    "num":"11",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-11.html"
                },
                {
                    "title":"第10集",
                    "num":"10",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-10.html"
                },
                {
                    "title":"第09集",
                    "num":"9",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-9.html"
                },
                {
                    "title":"第08集",
                    "num":"8",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-8.html"
                },
                {
                    "title":"第07集",
                    "num":"7",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-7.html"
                },
                {
                    "title":"第06集",
                    "num":"6",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-6.html"
                },
                {
                    "title":"第05集",
                    "num":"5",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-5.html"
                },
                {
                    "title":"第04集",
                    "num":"4",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-4.html"
                },
                {
                    "title":"第03集",
                    "num":"3",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-3.html"
                },
                {
                    "title":"第02集",
                    "num":"2",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-2.html"
                },
                {
                    "title":"第01集",
                    "num":"1",
                    "url":"http://qukantv.net/vod-play-id-52541-src-3-num-1.html"
                }
            ]
        },
        {
            "way":[
                {
                    "title":"第24集",
                    "num":"24",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-24.html"
                },
                {
                    "title":"第23集",
                    "num":"23",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-23.html"
                },
                {
                    "title":"第22集",
                    "num":"22",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-22.html"
                },
                {
                    "title":"第21集",
                    "num":"21",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-21.html"
                },
                {
                    "title":"第20集",
                    "num":"20",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-20.html"
                },
                {
                    "title":"第19集",
                    "num":"19",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-19.html"
                },
                {
                    "title":"第18集",
                    "num":"18",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-18.html"
                },
                {
                    "title":"第17集",
                    "num":"17",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-17.html"
                },
                {
                    "title":"第16集",
                    "num":"16",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-16.html"
                },
                {
                    "title":"第15集",
                    "num":"15",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-15.html"
                },
                {
                    "title":"第14集",
                    "num":"14",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-14.html"
                },
                {
                    "title":"第13集",
                    "num":"13",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-13.html"
                },
                {
                    "title":"第12集",
                    "num":"12",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-12.html"
                },
                {
                    "title":"第11集",
                    "num":"11",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-11.html"
                },
                {
                    "title":"第10集",
                    "num":"10",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-10.html"
                },
                {
                    "title":"第09集",
                    "num":"9",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-9.html"
                },
                {
                    "title":"第08集",
                    "num":"8",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-8.html"
                },
                {
                    "title":"第07集",
                    "num":"7",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-7.html"
                },
                {
                    "title":"第06集",
                    "num":"6",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-6.html"
                },
                {
                    "title":"第05集",
                    "num":"5",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-5.html"
                },
                {
                    "title":"第04集",
                    "num":"4",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-4.html"
                },
                {
                    "title":"第03集",
                    "num":"3",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-3.html"
                },
                {
                    "title":"第02集",
                    "num":"2",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-2.html"
                },
                {
                    "title":"第01集",
                    "num":"1",
                    "url":"http://qukantv.net/vod-play-id-52541-src-4-num-1.html"
                }
            ]
        },
        {
            "way":[
                {
                    "title":"第25集",
                    "num":"25",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-24.html"
                },
                {
                    "title":"第24集",
                    "num":"24",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-24.html"
                },
                {
                    "title":"第23集",
                    "num":"23",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-23.html"
                },
                {
                    "title":"第22集",
                    "num":"22",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-22.html"
                },
                {
                    "title":"第21集",
                    "num":"21",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-21.html"
                },
                {
                    "title":"第20集",
                    "num":"20",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-20.html"
                },
                {
                    "title":"第19集",
                    "num":"19",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-19.html"
                },
                {
                    "title":"第18集",
                    "num":"18",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-18.html"
                },
                {
                    "title":"第17集",
                    "num":"17",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-17.html"
                },
                {
                    "title":"第16集",
                    "num":"16",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-16.html"
                },
                {
                    "title":"第15集",
                    "num":"15",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-15.html"
                },
                {
                    "title":"第14集",
                    "num":"14",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-14.html"
                },
                {
                    "title":"第13集",
                    "num":"13",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-13.html"
                },
                {
                    "title":"第12集",
                    "num":"12",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-12.html"
                },
                {
                    "title":"第11集",
                    "num":"11",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-11.html"
                },
                {
                    "title":"第10集",
                    "num":"10",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-10.html"
                },
                {
                    "title":"第09集",
                    "num":"9",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-9.html"
                },
                {
                    "title":"第08集",
                    "num":"8",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-8.html"
                },
                {
                    "title":"第07集",
                    "num":"7",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-7.html"
                },
                {
                    "title":"第06集",
                    "num":"6",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-6.html"
                },
                {
                    "title":"第05集",
                    "num":"5",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-5.html"
                },
                {
                    "title":"第04集",
                    "num":"4",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-4.html"
                },
                {
                    "title":"第03集",
                    "num":"3",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-3.html"
                },
                {
                    "title":"第02集",
                    "num":"2",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-2.html"
                },
                {
                    "title":"第01集",
                    "num":"1",
                    "url":"http://qukantv.net/vod-play-id-52541-src-5-num-1.html"
                }
            ]
        },
        {
            "way":[
                {
                    "title":"第16集",
                    "num":"16",
                    "url":"http://qukantv.net/vod-play-id-52541-src-6-num-16.html"
                },
                {
                    "title":"第15集",
                    "num":"15",
                    "url":"http://qukantv.net/vod-play-id-52541-src-6-num-15.html"
                },
                {
                    "title":"第14集",
                    "num":"14",
                    "url":"http://qukantv.net/vod-play-id-52541-src-6-num-14.html"
                },
                {
                    "title":"第13集",
                    "num":"13",
                    "url":"http://qukantv.net/vod-play-id-52541-src-6-num-13.html"
                },
                {
                    "title":"第12集",
                    "num":"12",
                    "url":"http://qukantv.net/vod-play-id-52541-src-6-num-12.html"
                },
                {
                    "title":"第11集",
                    "num":"11",
                    "url":"http://qukantv.net/vod-play-id-52541-src-6-num-11.html"
                },
                {
                    "title":"第10集",
                    "num":"10",
                    "url":"http://qukantv.net/vod-play-id-52541-src-6-num-10.html"
                },
                {
                    "title":"第9集",
                    "num":"9",
                    "url":"http://qukantv.net/vod-play-id-52541-src-6-num-9.html"
                },
                {
                    "title":"第8集",
                    "num":"8",
                    "url":"http://qukantv.net/vod-play-id-52541-src-6-num-8.html"
                },
                {
                    "title":"第7集",
                    "num":"7",
                    "url":"http://qukantv.net/vod-play-id-52541-src-6-num-7.html"
                },
                {
                    "title":"第6集",
                    "num":"6",
                    "url":"http://qukantv.net/vod-play-id-52541-src-6-num-6.html"
                },
                {
                    "title":"第5集",
                    "num":"5",
                    "url":"http://qukantv.net/vod-play-id-52541-src-6-num-5.html"
                },
                {
                    "title":"第4集",
                    "num":"4",
                    "url":"http://qukantv.net/vod-play-id-52541-src-6-num-4.html"
                },
                {
                    "title":"第3集",
                    "num":"3",
                    "url":"http://qukantv.net/vod-play-id-52541-src-6-num-3.html"
                },
                {
                    "title":"第2集",
                    "num":"2",
                    "url":"http://qukantv.net/vod-play-id-52541-src-6-num-2.html"
                },
                {
                    "title":"第1集",
                    "num":"1",
                    "url":"http://qukantv.net/vod-play-id-52541-src-6-num-1.html"
                }
            ]
        }
    ]
}}'
        ];
        $curl = curl_init(); // 启动一个CURL会话      
        curl_setopt($curl, CURLOPT_URL, $url); // 要访问的地址              
        curl_setopt($curl, CURLOPT_HEADER, 0); // 显示返回的Header区域内容      
        curl_setopt($curl, CURLOPT_FOLLOWLOCATION, 1); // 使用自动跳转      
        curl_setopt($curl, CURLOPT_AUTOREFERER, 1); // 自动设置Referer      
        curl_setopt($curl, CURLOPT_POST, 1); // 发送一个常规的Post请求      
        curl_setopt($curl, CURLOPT_POSTFIELDS, $data); // Post提交的数据包      
//        curl_setopt($curl, CURLOPT_TIMEOUT, 150); // 设置超时限制防止死循环      
        
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1); // 获取的信息以文件流的形式返回      
        
        $tmpInfo = curl_exec($curl); // 执行操作      
        if (curl_errno($curl)) {      
           echo 'Errno'.curl_error($curl);      
        }      
//        print_r(curl_getinfo($curl));die;
        curl_close($curl); // 关键CURL会话      
        return $tmpInfo; // 返回数据      
    }
    
    public function actionB() {
        $str = $this->getParam('str');
        $arr = explode(',', $str);
        $kind = 0;
        $areaArr = [];
        $year = 0;
        $genre = '';
        foreach($arr as $key=>$item) {
            if($item == '电影') {
                $kind = 1;
            }else if($item == '电视剧') {
                $kind = 2;
            }else if($item == '综艺') {
                $kind = 3;
            }else if($item == '动画') {
                $kind = 4;
            }else if($item == '港台') {
                $areaArr = ['香港', '台湾'];
            }else if($item == '日韩') {
                $areaArr = ['日本', '韩国'];
            }else if($item == '欧美') {
                $areaArr = ['德国', '法国', '英国', '西班牙', '瑞典', '瑞士', '挪威', '奥地利', '意大利', '芬兰', '美国', '加拿大'];
            }else if(is_numeric($item)) {
                $year = $item;
            }else {
                $genre = $item;
            }
        }
        $result = [
            'area' => $areaArr,
            'kind' => $kind,
            'year' => $year,
            'genre' => $genre
        ];
        print_r($result);
    }
    
    public function actionE() {
        $arr = Yii::$app->redis->keys('FILM_HOT*');
        print_r($arr);die;
        Yii::$app->redis->del($arr);
    }
    
    
    
}

